Repository planetarium/NineChronicles.Headless, pull requests merged in 2021-02, with the labels that each got.

#268 docs: add secure mode document
  Docs/SECURE_MODE.md
Labels: documentation

#276 fix: remove 'AllowAllOrigins' CORS policy
  NineChronicles.Headless/GraphQLService.cs
Labels: bug

#273 feat: send cloudwatch logs periodically
  NineChronicles.Headless.Executable/AWSSink.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
Labels: bug

#249 Fix NullReferenceException with empty authorized miner state
  NineChronicles.Headless/NineChroniclesNodeService.cs
Labels: bug

#308 build: use static code analysis tool
  Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Common.ruleset
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: suggestion

#322 Document StateQuery
  NineChronicles.Headless/GraphTypes/ActionMutation.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/CostumeType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/ItemBaseType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/ItemUsableType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/ShopItemType.cs
  NineChronicles.Headless/GraphTypes/States/RankingInfoType.cs
  NineChronicles.Headless/GraphTypes/States/RankingMapStateType.cs
  NineChronicles.Headless/GraphTypes/States/ShopStateType.cs
Labels: documentation
