Repository planetarium/NineChronicles.Headless, pull requests merged in 2021-07, with the labels that each got.

#550 ci(stale): rename config filename
  .github/stale.yml
Labels: bug, ci

#542 add offset parameter to topmostblock query
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
Labels: graphql

#552 feat(graphql): transaction query headless
  NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: enhancement
