Repository planetarium/NineChronicles.Headless, pull requests merged in 2021-03, with the labels that each got.

#348 feat: introduce `chain tip` subcommand
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
  NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
  NineChronicles.Headless.Executable/Store/NoOpStateStore.cs
  NineChronicles.Headless.Executable/Store/StoreType.cs
  NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
  README.md
Labels: cli

#362 feat(cli): introduce `key` subcommand
  NineChronicles.Headless.Executable/Commands/KeyCommands.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/Utils/ConsolePasswordReader.cs
  NineChronicles.Headless.Executable/Utils/Utils.cs
  README.md
Labels: cli

#363 fix(graphql): resolve manually for field
  NineChronicles.Headless/GraphTypes/States/Models/Item/DecimalStatType.cs
Labels: bug

#365 feat(cli): add `--no-passphrase` option into `key` command
  NineChronicles.Headless.Executable.Tests/Commands/KeyCommandTest.cs
  NineChronicles.Headless.Executable.Tests/KeyStore/InMemoryKeyStore.cs
  NineChronicles.Headless.Executable/Commands/KeyCommands.cs
  NineChronicles.Headless.Executable/Program.cs
Labels: cli, suggestion

#367 feat(cli): introduce conversion subcommand
  NineChronicles.Headless.Executable.Tests/Commands/Key/ConversionCommandTest.cs
  NineChronicles.Headless.Executable/Commands/Key/ConversionCommand.cs
  NineChronicles.Headless.Executable/Commands/KeyCommands.cs
Labels: cli

#374 Fix broken build
  NineChronicles.Headless.Executable.sln
Labels: bug

#383 fix: support monorocksdb also in `chain tip` command
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
  NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
  NineChronicles.Headless.Executable/Store/StoreType.cs
  NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
Labels: bug, cli

#384 ci(gh-actions): fix invalid action input
  .github/workflows/deploy_gh_pages.yml
Labels: bug, ci

#382 ci(gh-actions): build graphql schema automatically
  .github/workflows/deploy_gh_pages.yml
  NineChronicles.Headless.Tests/Middleware/GraphQLSchemaMiddlewareTest.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/Middleware/GraphQLSchemaMiddleware.cs
  schema.graphql
Labels: ci

#328 Descriptions for tx, nodeStatus and peerChainState
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
  NineChronicles.Headless/GraphTypes/PeerChainStateQuery.cs
  NineChronicles.Headless/GraphTypes/TransactionType.cs
Labels: documentation

#396 fix(graphql): pass state & balance getter into subfields
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
  NineChronicles.Headless/BlockChainExtensions.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
Labels: bug
