Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-07, with the labels that each got.

#1375 Introduce PatchTableSheet query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: Small

#1405 Fix deploy gh pages workflow
  .github/workflows/deploy_gh_pages.yml
Labels: Extra Small

#1418 Add resolving fields about OrderId and TradableId in OrderBaseType
  NineChronicles.Headless/GraphTypes/States/Models/Order/OrderBaseType.cs
Labels: Extra Small

#1407 feat(graphql): introduce `AvatarStateType.index` field
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
Labels: api/graphql, Medium

#1374 feat(cli): introduce `--no-reduce-store` option
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: suggestion, cli, Extra Small

#1448 Add `MemoryStore` to `--store-type` option
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
  NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/Store/StoreType.cs
  NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
  README.md
Labels: enhancement
