Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-09, with the labels that each got.

#1533 Branch `StakeStateType.claimableBlockIndex` by block index
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
  NineChronicles.Headless/GraphTypes/States/StateContext.cs
Labels: bug, Small

#1550 Find previous raid id
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: Small

#1555 Fix typo
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
Labels: documentation, Extra Small

#1568 feat(graphql): deprecate GraphQL APIs to handle private key
  NineChronicles.Headless/GraphTypes/KeyStoreMutation.cs
  NineChronicles.Headless/GraphTypes/KeyStoreType.cs
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: api/graphql, Extra Small

#1573 Cherry raid id query
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: Small

#1572 chore: support bls public key in parser
  Libplanet.Headless/PropertyParser.cs
Labels: Extra Small

#1577 Use appsettings file to run headless server
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.json
  README.md
Labels: enhancement, cli, Extra Large

#1599 Change test port not to conflict with 'appsettings.json'
  NineChronicles.Headless.Executable.Tests/ProgramTest.cs
Labels: bug, test, Extra Small

#1597 remove ListKeys method in `PruneStates`
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
Labels: Extra Small

#1604 Merge 100300 into development
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: Small

#1602 Feature/commands from lib9c tools
  NineChronicles.Headless.Executable.Tests/Commands/AccountCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Commands/GenesisHelper.cs
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Executable/Commands/AccountCommand.cs
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
  NineChronicles.Headless.Executable/Commands/MarketCommand.cs
  NineChronicles.Headless.Executable/Commands/StateCommand.cs
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
  NineChronicles.Headless.Executable/Program.cs
Labels: enhancement, cli, Extra Large

#1541 Rc v100290 to development
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
  NineChronicles.Headless/GraphTypes/States/StateContext.cs
  README.md
Labels: Small
