Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-12, with the labels that each got.

#1731 feat: Add `currencyMintersAddress` query
  NineChronicles.Headless.Tests/GraphTypes/AddressQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/AddressQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: Medium

#1755 🧹 [PBFT] Added pbft branch to docker image workflow
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1704 Introduce Sentry Tracing on Action Execute
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/BlockChainService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: Medium

#1762 Nooooooooo Whyyyyyyyy
  NineChronicles.Headless.Executable/Configuration.cs
Labels: bug, Extra Small

#1765 Introduce `activateAccount` action GraphQL endpoint
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: Extra Small

#1772 ci(gh-actions): update actions used node12
  .github/workflows/build.yml
  .github/workflows/deploy_gh_pages.yml
  .github/workflows/deploy_ghpackages_docker.yml
  .github/workflows/lint.yml
  .github/workflows/push_docker_image.yml
  .github/workflows/release.yaml
Labels: ci, Extra Small

#1777 Unlink Lib9c.Tools to prepare deprecation
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  README.md
Labels: Extra Small

#1791 introduce: s3 logger
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/CredentialConfig.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
Labels: Extra Small

#1800 [Chore] Cleanup unused monstercollection subjects
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: Large

#1804 Correct setup-dotnet action version
  .github/workflows/deploy_gh_pages.yml
Labels: bug, ci, Extra Small
