Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-10, with the labels that each got.

#1615 Remove remaining BLS public key check
  Libplanet.Headless/PropertyParser.cs
Labels: Extra Small, pbft

#1610 Fix ActionEvalautionPublisher for concurrency
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Large

#1627 update `README.md` to latest
  README.md
Labels: Small

#1652 Add `StakeStates` field to `stateQuery`
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: api/graphql, Extra Small

#1649 Drop features related to AWS
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
Labels: Small

#1616 Fix invalid raider address query
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/AddressQuery.cs
Labels: Extra Small
