Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-06, with the labels that each got.

#1312 Configurable consensus peer
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Small, pbft

#1335 hotfix: Remove useless output
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
Labels: bug, cli

#1338 Cherry-pick: Remove useless output
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
Labels: bug, cli

#1343 Cherry-pick 2122c917c73ae971236ab12e6e8ff033e1ab7700
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: Small

#1345 Provide `bonusRewards` field in `StakeRegularRewardSheet`
  NineChronicles.Headless.Tests/GraphTypes/Abstractions/StakeRegularRewardsTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/Abstractions/StakeRewardsTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardRowTypeTest.cs
  NineChronicles.Headless/GraphTypes/Abstractions/StakeRegularRewardsType.cs
  NineChronicles.Headless/GraphTypes/Abstractions/StakeRewardsType.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularFixedRewardInfoType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
Labels: api/graphql, Medium

#1354 Introduce `TxResultType.exception..` fields
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
  NineChronicles.Headless/GraphTypes/TxResult.cs
  NineChronicles.Headless/GraphTypes/TxResultType.cs
Labels: api/graphql, Extra Small

#1359 fix(graphql): correct `claimableBlockIndex`
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
Labels: bug, api/graphql, Extra Small

#1373 feat(graphql): introduce `CrystalMonsterCollectionMultiplierSheet` type
  NineChronicles.Headless.Tests/GraphTypes/States/Models/CrystalMonsterCollectionMultiplierRowTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/CrystalMonsterCollectionMultiplierSheetTypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/CrystalMonsterCollectionMultiplierRowType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/CrystalMonsterCollectionMultiplierSheetType.cs
Labels: api/graphql, Medium

#1379 Fix flaky test
  NineChronicles.Headless.Executable.Tests/ProgramTest.cs
Labels: Extra Small
