Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-01, with the labels that each got.

#1020 Avoid NRE in GetStateBulk
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small

#1019 Setup devcontainer for GitHub Codespace
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Extra Small

#1023 Docker build for Apple Silicon
  Dockerfile.arm64v8
  Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
  NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
Labels: Small, No Changes

#1026 Support options for gRPC HTTP1 endpoint
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
  NineChronicles.Headless/Properties/RpcNodeServiceProperties.cs
Labels: suggestion, cli, Extra Small, api/rpc
