Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-08, with the labels that each got.

#1452 Update headless options
  NineChronicles.Headless.Executable/Program.cs
  README.md
Labels: documentation

#1454 Add `prune-states` command
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
Labels: Medium

#1459 detailed FungibleAssetValue info
  NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs
  NineChronicles.Headless/GraphTypes/CurrencyType.cs
  NineChronicles.Headless/GraphTypes/FungibleAssetValueWithCurrencyType.cs
Labels: Medium

#1474 Fix build
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
  NineChronicles.Headless/GraphTypes/ActionMutation.cs
Labels: bug, Extra Small

#1470 Rebuild genesis command
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  README.md
  config.json.example
Labels: documentation, enhancement, Large

#1488 Make GenesisCommandTest passes: resolve #1487
  NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
Labels: bug, ci, Small

#1495 use explorer graphtype for txResult and txStatus
  NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: Extra Small

#1496 Add Discord invitation button
  README.md
Labels: Extra Small
