Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-11, with the labels that each got.

#1655 Introduce raider list query
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/GraphTypes/AddressQuery.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: Extra Small

#1661 Introduce command `replay blocks`
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
Labels: Large

#1683 Throttle DAP subscription
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: Extra Small

#1682 Add ObserveOn on ActionEvaluationPublisher
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: bug, Extra Large

#1688 update gql subscription
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: Small

#1691 Port fixes & Release v100321-2
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: Extra Large

#1700 Release v100321-3
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: Medium

#1706 Separate libplanet explorer into a new endpoint
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/GraphQLServiceExtensions.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: api/graphql

#1702 Release v100321-3
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: Medium

#1708 Add timestamp to actionTxQuery
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
  NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: Extra Small

#1711 Release v100321-4
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
Labels: api/graphql, Extra Small

#1670 Update StakeRewardsType
  NineChronicles.Headless.Tests/GraphTypes/Abstractions/StakeRegularRewardsTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRewardEnumType.cs
Labels: Small

#1714 v100321-4 back-merge
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
Labels: Extra Small

#1709 Fix output messages of replay command
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
Labels: Extra Small

#1716 Introduce TransferAssets action query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/RecipientsInputType.cs
Labels: Small

#1717 Implement ClaimStakeReward interface and factory
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: enhancement, cli, Extra Small

#1720 Fix `createAvatar` action query
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: bug, Extra Small

#1723 Add extra field to evaluation of `BattleGrandFinale`
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#1725 Introduce runeEnhancement GQL endpoint
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: enhancement, api/graphql, Extra Small

#1733 Remove Lib9c.Tests from solution
  NineChronicles.Headless.Executable.sln
Labels: No Changes

#1732 Remove `DevLibplanetNodeService`
  Libplanet.Headless/Hosting/DevLibplanetNodeService.cs
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
  NineChronicles.Headless/ReorgPolicy.cs
Labels: Large

#1735 feat: Give miner break time
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: cli, Extra Small

#1737 Provide `appsettings.development.json`
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/appsettings.development.json
Labels: Small, configuration

#1741 Follow .NET default C# language version
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: Extra Small

#1743 Bump `SonarAnalyzer.CSharp` to `8.49.0.57237`
  Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
  NineChronicles.Headless.Executable/Commands/StateCommand.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/MonsterCollectionResultTypeTest.cs
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/GraphTypes/States/WorldBossKillRewardRecordType.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: Extra Small
