Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-02, with the labels that each got.

#1038 Use `Server Garbage Collection` mode
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
Labels: Extra Small

#1039 Capture HTTP requests
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
Labels: suggestion, Extra Small

#754 Add `shardedShop` in `stateQuery`.
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/ShardedShopStateV2TypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/Models/Order/OrderBaseType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Order/OrderDigestType.cs
  NineChronicles.Headless/GraphTypes/States/ShardedShopStateV2Type.cs
Labels: api/graphql, Large

#1046 fix(graphql): seek HTTP request buffer to begin
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
Labels: bug, api/graphql, Extra Small

#1047 fix(graphql): prevent to harm HTTP/2 (RPC) messages
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
Labels: bug, api/graphql, Extra Small, api/rpc

#1048 Enable docker-from-docker in VS Code devcontainer
  .devcontainer/devcontainer.json
Labels: Extra Small

#1044 Improve/genesis additional actions
  NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
Labels: Small

#1052 [Bot] Merge rc-v100102 to development
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
Labels: Extra Small

#1049 E2E test
  NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
  NineChronicles.Headless.Executable.Tests/ProgramTest.cs
  NineChronicles.Headless.Executable/Program.cs
Labels: suggestion, api/graphql, test, Small, api/rpc

#1063 Tarog star update graphql actions
  NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
  NineChronicles.Headless/GraphTypes/ActionMutation.cs
Labels: Small

#893 feat(cli): use default tx lifetime
  NineChronicles.Headless.Executable/Program.cs
Labels: Extra Small

#1062 Correct `--rpc-http-server` option feature
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/Properties/GraphQLNodeServiceProperties.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
  NineChronicles.Headless/Properties/RpcNodeServiceProperties.cs
Labels: bug, api/graphql, Small, api/rpc

#1071 Build Docker images for every tag
  .github/workflows/push_docker_image.yml
Labels: ci, Small

#1074 Fix GitHub Actions context expansions
  .github/workflows/push_docker_image.yml
Labels: bug, ci, Extra Small

#1082 Compress action evaluation
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small
