Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-04, with the labels that each got.

#1170 Fix timeout when RankingBattle failed
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#1178 Trigger Submodule Updater on every push to rc-v* branches
  .github/workflows/release.yaml
Labels: ci, submodule, Extra Small

#1153 Use JsonFormatter for multiline logging
  NineChronicles.Headless.Executable/appsettings.json
Labels: Extra Small

#1192 Install curl
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
Labels: Extra Small

#1194 Update target to net6
  .github/workflows/build.yml
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
  Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: Extra Small

#1086 Prevent returning null on stageTxV2 mutation
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
Labels: bug, api/graphql, Extra Small

#1206 feat(cli): print raw action into stdout as default
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
Labels: cli, Small

#1198 Remove stale bot configuration
  .github/stale.yml
Labels: bug, ci, Extra Small

#1188 Fix weekly arena ordered infos
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: Extra Small
