Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-05, with the labels that each got.

#1239 Introduce `query.actionQuery`
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: api/graphql, Small

#1249 Revert features related to `Stake`
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: Small

#1246 Introduce CRYSTAL action query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: Medium

#1263 Introduce model queries related to `Stake`
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeAchievementsTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardRowTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardSheetTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardRowType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
  NineChronicles.Headless/GraphTypes/States/StakeAchievementsType.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
Labels: api/graphql, Large

#1247 Introduce CRYSTAL related model queries
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
Labels: Medium

#1270 Introduce TransferAsset query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/CurrencyType.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: Small

#1264 docs: introduce how to build genesis
  Docs/BUILD_GENESIS.md
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
Labels: documentation, cli, Extra Small

#1276 Deprecate unused parameter
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
  README.md
Labels: Extra Small

#1278 Provides action commands related to `Stake`
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
Labels: cli, Small

#1279 Merge `feature/stake` into `2022q2`
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ActionCommand.cs
  NineChronicles.Headless.Executable/Commands/TxCommand.cs
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeAchievementsTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardRowTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardSheetTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardRowType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
  NineChronicles.Headless/GraphTypes/States/StakeAchievementsType.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
Labels: Large

#1286 Fix invalid currency in transferAsset action query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/CurrencyType.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: bug, api/graphql, Small

#1292 fix(graphql): correct non-nullable types
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
Labels: bug, api/graphql, Extra Small

#1293 Merge `feature/stake` to `2022q2`
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
Labels: Extra Small

#1295 Merge `2022q2` to `previewnet`
  NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
Labels: Extra Small

#1304 fix(graphql): correct `StakeStateType.claimableBlockIndex`
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
Labels: Extra Small

#1305 Merge `2022q2` to `previewnet`
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
Labels: Extra Small

#1307 chore: consensus argument
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable.Tests/ProgramTest.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Small, pbft
