Repository planetarium/NineChronicles.Headless, pull requests merged in 2022-03, with the labels that each got.

#1059 Introduce GetRawAvatarStates
  NineChronicles.Headless/AccountStateGetterExtension.cs
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small

#1105 Fix invalid serialize address
  NineChronicles.Headless.Tests/GraphTypes/States/Models/MonsterCollectionRowTypeTest.cs
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small

#1126 chore: ci build branch name changed
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1113 Decrease `RocksDBStore`'s `dbConnectionCacheSize` option
  NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
Labels: Extra Small

#1081 Add inner exception information for StageTxV2
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
Labels: Extra Small

#1112 Prepare .NET 6 bump
  NineChronicles.Headless.Executable.Tests/ProgramTest.cs
  NineChronicles.Headless/Controllers/GraphQLController.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
Labels: Extra Small

#1143 Use HTTPS for submodule URLs
  .gitmodules
Labels: Extra Small

#1142 feat(graphql): introduce `nodeStatus.appProtocolVersion`
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
Labels: api/graphql, Extra Small

#1155 Release automation
  .github/workflows/release.yaml
Labels: ci, Extra Small
