Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-07, with the labels that each got.

#2115 Add CombinationSlot query in AvatarStateType
  NineChronicles.Headless.Tests/Common/Fixtures.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/CombinationSlotStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs
Labels: api/graphql, Small

#2124 feat: improve state query `garages` result schema
  NineChronicles.Headless.Tests/GraphTypes/StateQueryTest.cs
  NineChronicles.Headless/GraphTypes/StateQueryFields/Garages.cs
  NineChronicles.Headless/GraphTypes/States/GaragesType.cs
  NineChronicles.Headless/GraphTypes/States/Models/Garage/FungibleItemGarageType.cs
Labels: Extra Small

#2136 fix: recover `RemoteActionEvaluator` feature
  Lib9c.StateService/appsettings-schema.json
  Lib9c.StateService/appsettings.json
  Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
  Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
  Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockState.cs
Labels: bug, Large, dx

#2138 feat: store updated states' addresses at least
  Libplanet.Headless/ReducedStore.cs
Labels: suggestion, Extra Small, dx

#2139 fix: close xml tag
  Libplanet.Headless/ReducedStore.cs
Labels: bug, documentation, No Changes

#2140 fix: correct `ForkableActionEvaluator`'s configuration parsing logic
  Libplanet.Headless/Hosting/ForkableActionEvaluatorConfiguration.cs
  NineChronicles.Headless.Executable/Program.cs
Labels: bug, Extra Small, configuration

#2141 fix: correct `ForkableActionEvaluator`'s configuration parsing logic
  NineChronicles.Headless.Executable/Program.cs
Labels: bug, configuration

#2147 fix: deprecate `NineChronicles.Headless.GraphTypes.CurrencyInputType`
  NineChronicles.Headless/GraphTypes/CurrencyInputType.cs
Labels: api/graphql, Extra Small

#2153 ci(gh-actions): check typos
  .github/workflows/lint.yml
  NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphTypes/ActivationStatusMutation.cs
  _typos.toml
Labels: Extra Small, configuration

#2116 Make remote-tx subcommand for replay command
  Libplanet.Extensions.RemoteBlockChainStates/Libplanet.Extensions.RemoteBlockChainStates.csproj
  NineChronicles.Headless.Executable/Commands/ReplayCommand.Queries.cs
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
Labels: cli, Medium, Squash Needed

#2158 fix(cli): remove private key from log
  NineChronicles.Headless.Executable.Tests/Commands/ValidationCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ValidationCommand.cs
Labels: bug, cli, Extra Small

#2157 fix: use `NCDevActionLoader` when DevEx configuration
  NineChronicles.Headless/NCActionUtils.cs
Labels: bug, Extra Small

#2159 chore: remove longfin from auto_assign list
  .github/auto_assign.yml
Labels: Extra Small

#2164 ci(gh-actions): disable building lib9c-stateserivce Docker image
  .github/workflows/push_docker_image.yml
  Dockerfile.lib9c-stateservice.amd64
  Dockerfile.lib9c-stateservice.arm64v8
Labels: bug, ci, Small

#2165 ci(gh-actions): disable tagging lib9c-stateservice
  .github/workflows/push_docker_image.yml
Labels: bug, ci, Extra Small

#2162 feat: Cleanup agent addresses in SubscribeBalance
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: Extra Small, Squash Needed

#2167 Revert "feat: Cleanup agent addresses in SubscribeBalance (#2162)"
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: Extra Small

#2169 [Feature] subscribe balance after cleanup
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: Extra Small
