Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-06, with the labels that each got.

#2072 Update rate limit
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
  NineChronicles.Headless/Middleware/CustomRateLimitProcessor.cs
Labels: Extra Small

#2076 downgrade headless to `.NET6`
  .github/workflows/build.yml
  .github/workflows/deploy_gh_pages.yml
  .github/workflows/lint.yml
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
  Dockerfile.lib9c-stateservice.amd64
  Dockerfile.lib9c-stateservice.arm64v8
  Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
  Lib9c.StateService/Lib9c.StateService.csproj
  Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests.csproj
  Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
  Libplanet.Extensions.ForkableActionEvaluator.Tests/Libplanet.Extensions.ForkableActionEvaluator.Tests.csproj
  Libplanet.Extensions.ForkableActionEvaluator/Libplanet.Extensions.ForkableActionEvaluator.csproj
  Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
  Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  Libplanet.Extensions.RemoteBlockChainStates/Libplanet.Extensions.RemoteBlockChainStates.csproj
  Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
  NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
  NineChronicles.Headless/NineChronicles.Headless.csproj
  global.json
Labels: Small

#2079 Update `push docker image` action trigger
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#2080 Automate validating GitHub Actions workflow
  .github/workflows/lint.yml
  .github/workflows/push_docker_image.yml
  .github/workflows/validate-github-actions-workflows.yaml
Labels: bug, Extra Small

#2085 Fix Typo
  Libplanet.Headless/ReducedStore.cs
Labels: No Changes

#2090 add submodule-updater to bump headless submodule in `DataProvider`
  .github/workflows/update-submodule.yaml
Labels: Extra Small

#2091 ci(gh-actions): remove `deploy_gh_pages` workflow
  .github/workflows/deploy_gh_pages.yml
Labels: bug, ci, Small

#2094 Add PreviousStates for rendering of BattleArena
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#2103 Validate tx in grpc PutTransaction
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small

#2105 Development merge v200030 2
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small

#2106 Add gas config to createUnsignedTx query
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: api/graphql, Extra Small

#2107 Check fav deltas contain NCG
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: bug, api/graphql

#2109 Merge `main` into `development`
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: Extra Small

#2110 Deprecate activation-related queries
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/ActivationStatusMutation.cs
  NineChronicles.Headless/GraphTypes/ActivationStatusQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: api/graphql, Extra Small
