Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-03, with the labels that each got.

#1936 update gql logger level
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
Labels: Extra Small

#1921 Introduce script to build multiple Lib9c versions for pluggable lib9c
  .versions.toml
  Docs/PLUGGABLE_LIB9C.md
  prepare-pluggable-lib9c.py
Labels: Small

#1927 Include Pluggable Lib9c DLLs in container image
  Dockerfile
Labels: Extra Small

#1938 Track meter always
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
Labels: bug, Extra Small

#1945 Track meter always
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
Labels: Extra Small

#1946 Fix: submit consensusTransport param to Swarm
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
Labels: Extra Small

#1950 Fix startIndex as nullable and use tip index as default
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
Labels: Extra Small

#1954 Introduce replay blocks query
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
Labels: Extra Small

#1959 Add json log config
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.internal.json
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: Extra Small

#1965 feat: arguments for consensus
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Extra Small

#1966 fix: lint
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Extra Small

#1970 Add Json logging config
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.internal.json
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: Extra Small
