Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-05, with the labels that each got.

#2008 Support additional metrics
  NineChronicles.Headless/NineChroniclesNodeService.cs
Labels: enhancement, Extra Small, metrics

#2018 Update APV to latest
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: Extra Small

#2012 Implement `RemoteActionEvaluator`
  .github/workflows/push_docker_image.yml
  Dockerfile.lib9c-stateservice
  Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  Lib9c.StateService/Lib9c.StateService.csproj
  Lib9c.StateService/Program.cs
  Lib9c.StateService/Properties/launchSettings.json
  Lib9c.StateService/appsettings.Development.json
  Lib9c.StateService/appsettings.json
  Libplanet.Extensions.RemoteActionEvaluator.Tests/ActionEvaluationSerializerTest.cs
  Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
  Libplanet.Extensions.RemoteActionEvaluator.Tests/Usings.cs
  Libplanet.Extensions.RemoteActionEvaluator/AccountStateDelta.cs
  Libplanet.Extensions.RemoteActionEvaluator/AccountStateDeltaMarshaller.cs
  Libplanet.Extensions.RemoteActionEvaluator/ActionContext.cs
  Libplanet.Extensions.RemoteActionEvaluator/ActionContextMarshaller.cs
  Libplanet.Extensions.RemoteActionEvaluator/ActionEvaluation.cs
  Libplanet.Extensions.RemoteActionEvaluator/ActionEvaluationMarshaller.cs
  Libplanet.Extensions.RemoteActionEvaluator/AssemblyInfo.cs
  Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  Libplanet.Extensions.RemoteActionEvaluator/PreEvaluationBlockMarshaller.cs
  Libplanet.Extensions.RemoteActionEvaluator/Random.cs
  Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
  Libplanet.Extensions.RemoteActionEvaluator/RemoteBlockChainStates.cs
  Libplanet.Extensions.RemoteActionEvaluator/RemoteEvaluationRequest.cs
  Libplanet.Extensions.RemoteActionEvaluator/RemoteEvaluationResponse.cs
  Libplanet.Extensions.RemoteActionEvaluator/TransactionMarshaller.cs
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Executable.sln
Labels: Extra Large

#2019 Correct Lib9c.StateService build
  Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Labels: bug

#2021 Correct `Libplanet.Extensions.RemoetActionEvaluator` build
  Libplanet.Extensions.RemoteActionEvaluator.Tests/ActionEvaluationSerializerTest.cs
Labels: bug, Extra Small

#2023 Introduce `ForkableActionEvaluator`
  Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests.csproj
  Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Usings.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDeltaMarshaller.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContext.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluation.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
  Libplanet.Extensions.ActionEvaluatorCommonComponents/PreEvaluationBlockMarshaller.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/Random.cs
  Libplanet.Extensions.ActionEvaluatorCommonComponents/TransactionMarshaller.cs
  Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
  Libplanet.Extensions.ForkableActionEvaluator.Tests/Libplanet.Extensions.ForkableActionEvaluator.Tests.csproj
  Libplanet.Extensions.ForkableActionEvaluator.Tests/Usings.cs
  Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
  Libplanet.Extensions.ForkableActionEvaluator/HardForkRouter.cs
  Libplanet.Extensions.ForkableActionEvaluator/Libplanet.Extensions.ForkableActionEvaluator.csproj
  Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
  NineChronicles.Headless.Executable.sln
Labels: Large

#2025 Fix json log rotation limit from 500M to 100M
  NineChronicles.Headless.Executable/Program.cs
Labels: Extra Small

#2024 Support `ActionEvaluator` configuration
  Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  Libplanet.Headless/Hosting/ActionEvaluatorType.cs
  Libplanet.Headless/Hosting/DefaultActionEvaluatorConfiguration.cs
  Libplanet.Headless/Hosting/ForkableActionEvaluatorConfiguration.cs
  Libplanet.Headless/Hosting/IActionEvaluatorConfiguration.cs
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  Libplanet.Headless/Hosting/RemoteActionEvaluatorConfiguration.cs
  Libplanet.Headless/Libplanet.Headless.csproj
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Medium

#2029 Fix gql error format to follow global Logger
  NineChronicles.Headless/GraphQLService.cs
Labels: Extra Small

#2034 ci(gh-actions): test all test projects
  .github/workflows/build.yml
  Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
Labels: ci, Extra Small

#2035 ci(gh-actions): build and test with DevEx configuration too
  .github/workflows/build.yml
  NineChronicles.Headless.Executable/Program.cs
Labels: ci, Extra Small

#2039 Make `RemoteBlockChainStates` configurable in `Lib9c.StateService`
  Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  Lib9c.StateService/Program.cs
Labels: Extra Small

#2040 ci(gh-actions): build lib9c-stateservice with mutli arch support
  .github/workflows/push_docker_image.yml
  Dockerfile.lib9c-stateservice.amd64
  Dockerfile.lib9c-stateservice.arm64v8
Labels: ci, Extra Small

#2050 Correct `RemoteBlockChainStates.GetTrie()` implementation
  Libplanet.Extensions.RemoteActionEvaluator/RemoteBlockChainStates.cs
Labels: bug, Extra Small

#2052 fix(cli): correct replay command
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
Labels: bug, cli, Extra Small

#2056 Separate shared classes as a new project
  Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
  Lib9c.StateService.Shared/RemoteEvaluationRequest.cs
  Lib9c.StateService.Shared/RemoteEvaluationResponse.cs
  Lib9c.StateService/Controllers/RemoteEvaluationController.cs
  Lib9c.StateService/Lib9c.StateService.csproj
  Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
  Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
  NineChronicles.Headless.Executable.sln
Labels: bug, ci, Extra Small

#2057 feat(cli): make `ConsensusReactorOption.TargetBlockInterval` configurable
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: suggestion, cli, Extra Small

#2069 ci(gh-actions): refactor docker image build workflow
  .github/workflows/push_docker_image.yml
Labels: ci, Small

#2070 Add requiredBlockIndex field
  NineChronicles.Headless.Tests/GraphTypes/States/Models/EquipmentTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/ItemBaseType.cs
Labels: Extra Small
