Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-08, with the labels that each got.

#2173 Add AssemblyName to Executable to make shortcut naming
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
Labels: Extra Small, Squash Needed, configuration

#2174 Implement `StateServices` feature
  NineChronicles.Headless.Executable.sln
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
  NineChronicles.Headless/Properties/StateServiceManagerServiceOptions.cs
  NineChronicles.Headless/Services/StateService.cs
  NineChronicles.Headless/Services/StateServiceManagerService.cs
Labels: Medium

#2182 Add equipped filter into equipments field
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
Labels: api/graphql, Extra Small

#2179 Add avatars query
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: api/graphql, Extra Small

#2181 Introduce arenaInformation GQL endpoint
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/ArenaInformationType.cs
Labels: enhancement, api/graphql, Small

#2183 Introduce runes query in avatarState GraphQL
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/RuneStateType.cs
Labels: enhancement, api/graphql, Extra Small

#2180 track client count by device
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphTypes/RpcInformationQuery.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs
Labels: Medium

#2186 fix: use default ActionEvaluator
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: bug, Extra Small, configuration

#2190 Add `itemSubType` argument to `InventoryType.equipments` field
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
Labels: api/graphql, Extra Small

#2192 Revert "Add AssemblyName to Executable to make shortcut naming (#2173)"
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
Labels: bug, Extra Small

#2193 disable buffering
  NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
  NineChronicles.Headless/Middleware/IpBanMiddleware.cs
Labels: Extra Small

#2195 Some GraphQL features
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: api/graphql, Medium

#2198 ci(gh-actions): recover deploy_gh_pages
  .github/workflows/deploy_gh_pages.yaml
  .gitignore
  resources/logo.png
  spectaql-config.yaml
Labels: documentation, Small, dx

#2201 ci(gh-actions): increase delay time between startup and fetching
  .github/workflows/deploy_gh_pages.yaml
Labels: ci, Extra Small

#2202 ci(gh-actions): increase delay time between startup and fetching
  .github/workflows/deploy_gh_pages.yaml
Labels: ci

#2203 feat(graphql): provide `ids` filter on `equipments` query
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
Labels: api/graphql, Extra Small

#2204 🧹 Clean up staled pluggable lib9c
  .versions.toml
  Dockerfile
  prepare-pluggable-lib9c.py
Labels: Small

#2200 Add InventoryAddress field for AvatarStateType
  .gitignore
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
Labels: api/graphql, Extra Small

#2207 Force `claim_stake_reward6`
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: bug, Extra Small

#2217 add account management feature
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Tests/GraphQLStartupTest.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs
  NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
  NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
  NineChronicles.Headless/Properties/MultiAccountManagerProperties.cs
Labels: Large

#2227 don't use multiaccount middleware if not enabled
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
Labels: Extra Small

#2228 Exp field needs resolve function
  NineChronicles.Headless/GraphTypes/States/Models/Item/EquipmentType.cs
Labels: bug, api/graphql, Extra Small
