Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-09, with the labels that each got.

#2234 fix(graphql): return null instead of errors
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: bug, api/graphql, Extra Small

#2239 Add .gitallowed for git secrets
  .gitallowed
Labels: Extra Small

#2243 Support regex for `transaction.ncTransactions`' actionType argument
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: api/graphql, Extra Small

#2242 fix duplicate publisher in RPC mode
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
Labels: Extra Small

#2245 Set tipChanged subject's buffer size to 1
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
Labels: bug, Extra Small

#2254 Update account management
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Tests/GraphQLStartupTest.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/GraphTypes/MultiAccountType.cs
  NineChronicles.Headless/GraphTypes/RpcInformationQuery.cs
  NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
  NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
Labels: Large

#2256 ci: push docker image for testing
  .github/workflows/push_docker_image.yml
Labels: Extra Small
