Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-12, with the labels that each got.

#2332 feat: resolve plugin path
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
Labels: Extra Small

#2329 Introduce JWT Authentication for GraphQL(Optional)
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/Middleware/JwtAuthenticationMiddleware.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
  NineChronicles.Headless/Properties/JwtOptions.cs
Labels: Medium

#2342 PDX-203: add config.schema.json
  config.json.example
  config.schema.json
Labels: cli, Small, configuration

#2348 add rocksdb-related dependencies
  Dockerfile.amd64
Labels: Extra Small

#2351 configure arena list sync worker for avoid memory pressure
  NineChronicles.Headless.Executable/Program.cs
Labels: Extra Small

#2354 Add detail to graphQL exceptions
  NineChronicles.Headless/GraphQLService.cs
Labels: Extra Small

#2349 PDX-204: Add GetAdditionalActionBases to genesis cli command
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  config.schema.json
Labels: Extra Small

#2356 🧹 Remove unused HTTP endpoints
  NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
  NineChronicles.Headless/Controllers/GraphQLController.cs
Labels: Large, api/http, deprecation

#2366 Add fungibleItemId on inventory item
  NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryItemType.cs
Labels: Extra Small

#2364 update snapshot command to latest
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
Labels: Large

#2367 ACS Handle redis, resapi timeout
  NineChronicles.Headless/Services/RedisAccessControlService.cs
  NineChronicles.Headless/Services/RestAPIAccessControlService.cs
Labels: Extra Small
