Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-04, with the labels that each got.

#1911 development merge Main v100371
  NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
Labels: Extra Small

#1973 Add json logging configuration
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.internal.json
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: Extra Small

#1981 Update `appsettings.mainnet.json` for v200000
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: configuration

#1982 Apply PBFT settings
  .gitignore
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
  NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
  README.md
  config.json
  config.json.example
Labels: enhancement

#1994 Action should not be null
  NineChronicles.Headless/GraphTypes/ActionQuery.DevEx.cs
Labels: bug

#2004 Bugfix/monster collection gql
  NineChronicles.Headless/GraphTypes/StateQuery.cs
Labels: bug, api/graphql
