Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-01, with the labels that each got.

#1799 Add snapshot feature to chain command
  NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
  NineChronicles.Headless.Executable/Commands/ChainCommand.cs
  README.md
Labels: Extra Large

#1806 add workflow dispatch trigger to build and push step
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1807 Ci/build trigger
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1816 Correct actions count
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
Labels: Extra Small

#1819 update TrustedAppProtocolVersionSignerStrings
  NineChronicles.Headless.Executable/appsettings.mainnet.json
Labels: Extra Small

#1826 Introduce JSON schema for appsettings.json
  .github/workflows/lint.yml
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless.Executable/appsettings.internal.json
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless.Executable/appsettings.mainnet.json
  NineChronicles.Headless.Executable/appsettings.previewnet.json
Labels: Small

#1803 [Feature] ReplaySubject to Subject
  NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: Extra Small

#1831 Improve `appsettings-schema.json`
  NineChronicles.Headless.Executable/appsettings-schema.json
Labels: Extra Small

#1833 Intorduce configuration for `StaticActionTypeLoader`
  Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/ActionTypeLoaderConfiguration.cs
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/StaticActionTypeLoaderConfiguration.cs
  NineChronicles.Headless.Executable/appsettings-schema.json
  NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
  NineChronicles.Headless.Tests/Common/StaticActionTypeLoaderSingleton.cs
  NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Large, configuration

#1842 [Feature] Introduce github release CI
  .github/bin/constants.sh
  .github/bin/dist-github-release.sh
  .github/bin/dist-pack.sh
  .github/bin/github-release.sh
  .github/workflows/release.yaml
  .gitignore
Labels: Medium

#1843 cherry pick a04b7e771225393230d5b3f8939c18f66f36f666
  .github/bin/constants.sh
  .github/bin/dist-github-release.sh
  .github/bin/dist-pack.sh
  .github/bin/github-release.sh
  .github/workflows/release.yaml
  .gitignore
Labels: Medium

#1844 Rename `IStoreExtensions` -> `StoreExtensions`
  NineChronicles.Headless.Executable.Tests/Store/StoreExtensionsTest.cs
  NineChronicles.Headless.Executable/Store/StoreExtensions.cs
Labels: Extra Small

#1837 Add graphql endpoints to essential game actions
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/CombinationConsumable.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/CombinationEquipment.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/DailyReward.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/HackAndSlash.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/HackAndSlashSweep.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/ItemEnhancement.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/RapidCombination.cs
Labels: api/graphql, Extra Large

#1834 [DevEx]Add `createOrReplaceAvatar` action query
  NineChronicles.Headless/GraphTypes/ActionQuery.DevEx.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/Input/ItemIdAndEnhancementType.cs
Labels: Small
