Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-02, with the labels that each got.

#1869 Fix release workflow bug
  .github/workflows/release.yaml
Labels: Extra Small

#1872 Provide metrics for NineChronicles node
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
  NineChronicles.Headless/NineChroniclesNodeService.cs
Labels: enhancement, Extra Small

#1873 fix syntax error
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1874 fix syntax error
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#1855 feat: `PetEnhancement` graphQL query
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldTypeInheritor.cs
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/PetEnhancementFieldTypeTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldType.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFieldTypes/PetEnhancementFieldType.cs
Labels: Large

#1861 Refactor genesis command
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  README.md
  config.json.example
Labels: Extra Small, pbft

#1858 add rate limit feature
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Executable/appsettings.json
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: Extra Small

#1882 Update pbft logger
  NineChronicles.Headless.Executable/Program.cs
Labels: Extra Small

#1898 fix: build errors
  NineChronicles.Headless.Executable.sln
Labels: No Changes

#1905 Bump OpenTelemetry
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: dependencies, Extra Small, metrics
