Repository planetarium/NineChronicles.Headless, pull requests merged in 2023-11, with the labels that each got.

#2279 Use Cocona.Docs
  .github/workflows/deploy_gh_pages.yaml
  NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
  NineChronicles.Headless.Executable/Program.cs
  README.md
Labels: documentation, Medium, dx

#2280 Deploy `index.html` also to gh-pages
  .github/workflows/deploy_gh_pages.yaml
  Docs/resources/landing.html
Labels: documentation, Extra Small

#2282 Introduce ClaimItems GQL endpoint
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/ClaimItems.cs
  NineChronicles.Headless/GraphTypes/Input/ClaimDataInputType.cs
Labels: enhancement, api/graphql, Medium

#2283 fix: warning disable CS0618 about CombinationSlotState.UnlockStage
  NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs
Labels: Extra Small

#2286 🔀 Merge 62 to development
  NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs
Labels: Extra Small

#2292 🔧 fix: remove diff
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#2295 🔀 merge: release/71 into main
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#2281 Tweak genesis command
  NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
  NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
  README.md
  config.json.example
Labels: Medium, Squash Needed

#2304 update acs log level to verbose
  NineChronicles.Headless/Services/RedisAccessControlService.cs
Labels: Extra Small

#2306 set timeout to 0.5s
  NineChronicles.Headless/Services/RedisAccessControlService.cs
Labels: Extra Small

#2307 🔨 PDX-136: Fix ncTransactions bug when startingBlockIndex is the same as the tip index
  NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: bug, api/graphql, Extra Small

#2308 change some AEP logs to verbose level
  NineChronicles.Headless/ActionEvaluationPublisher.cs
Labels: Extra Small

#2313 Add memo to claimItems GQL
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/ClaimItems.cs
Labels: enhancement, api/graphql, Extra Small

#2315 compress csv data in IBlockChainService.GetSheets
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/BlockChainService.cs
  NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs
Labels: Extra Small

#2309 PDX-126: update transferAsset to accept custom ticker
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
Labels: Small

#2316 Refactor caching
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Tests/GraphQLStartupTest.cs
  NineChronicles.Headless.Tests/GraphQLTestUtils.cs
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StateQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
  NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
  NineChronicles.Headless/ActionEvaluationPublisher.cs
  NineChronicles.Headless/ArenaParticipantsWorker.cs
  NineChronicles.Headless/BlockChainService.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StateQuery.cs
  NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
  NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
  NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
  NineChronicles.Headless/GraphTypes/States/StateContext.cs
  NineChronicles.Headless/StateMemoryCache.cs
Labels: Small

#2318 detailed log arena list worker
  NineChronicles.Headless/ArenaParticipantsWorker.cs
Labels: Extra Small

#2326 Introduce TransactionResults query
  NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
  NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
Labels: Small

#2321 [Feature] Implement Acc bulk insert
  NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
Labels: Extra Small

#2322 [Feature] Add Restapi acs
  NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
  NineChronicles.Headless/Services/AccessControlServiceFactory.cs
  NineChronicles.Headless/Services/RedisAccessControlService.cs
  NineChronicles.Headless/Services/RestAPIAccessControlService.cs
  NineChronicles.Headless/Services/SQLiteAccessControlService.cs
Labels: Small
