Repository planetarium/NineChronicles.Headless, pull requests merged in 2024-04, with the labels that each got.

#2439 Backmerge 120
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless/GraphTypes/ActionQuery.cs
  NineChronicles.Headless/GraphTypes/ActionQueryFields/RetrieveAvatarAssets.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: Small

#2449 Fix lint
  NineChronicles.Headless/ArenaParticipantsWorker.cs
Labels: bug, question

#2454 Bump OpenTelemetry-related dependencies
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/Middleware/JwtAuthenticationMiddleware.cs
  NineChronicles.Headless/NineChronicles.Headless.csproj
Labels: dependencies

#2460 hotfix(v200170): Disable .NET runtime instruments
  NineChronicles.Headless.Executable/Program.cs
Labels: bug, metrics, observability
