Repository planetarium/NineChronicles.Headless, pull requests merged in 2024-09, with the labels that each got.

#2567 Fix `ActionCommandTest`
  NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
Labels: bug

#2572 ci(gh-actions): remove invalid option
  .github/workflows/deploy_gh_pages.yaml
Labels: bug, ci

#2583 Fix broken tests
  NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
  NineChronicles.Headless.Tests/Common/Fixtures.cs
Labels: bug

#2586 Write invitations to developer portal
  README.md
Labels: documentation

#2540 Refactor with repository pattern
  NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless.Tests/Action/ActionContext.cs
  NineChronicles.Headless.Tests/GraphQLTestUtils.cs
  NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
  NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
  NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
  NineChronicles.Headless/BlockChainContext.cs
  NineChronicles.Headless/Domain/Model/BlockChain/Block.cs
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/GraphTypes/BlockHeaderType.cs
  NineChronicles.Headless/GraphTypes/NodeStatus.cs
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
  NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/NineChroniclesNodeService.cs
  NineChronicles.Headless/Repositories/BlockChain/BlockChainRepository.cs
  NineChronicles.Headless/Repositories/BlockChain/IBlockChainRepository.cs
  NineChronicles.Headless/Repositories/StateTrie/IStateTrieRepository.cs
  NineChronicles.Headless/Repositories/StateTrie/StateTrieRepository.cs
  NineChronicles.Headless/Repositories/Transaction/ITransactionRepository.cs
  NineChronicles.Headless/Repositories/Transaction/TransactionRepository.cs
  NineChronicles.Headless/Repositories/WorldState/IWorldStateRepository.cs
  NineChronicles.Headless/Repositories/WorldState/WorldStateRepository.cs
  NineChronicles.Headless/StandaloneContext.cs
Labels: enhancement, dx
