Repository planetarium/NineChronicles.Headless, pull requests merged in 2024-11, with the labels that each got.

#2605 Introduce new GQL: lastClearedStage
  NineChronicles.Headless/GraphTypes/States/Models/World/ClearedStageType.cs
  NineChronicles.Headless/GraphTypes/States/Models/World/WorldInformationType.cs
Labels: enhancement

#2624 ci: bump peaceiris/actions-gh-pages action to v4
  .github/workflows/deploy_gh_pages.yaml
Labels: ci, dependencies

#2625 chore: update dependabot conf to bump GitHub Actions automatically
  .github/dependabot.yml
Labels: ci, dependencies

#2621 ci: use setup-qemu-action instead
  .github/workflows/push_docker_image.yml
  Dockerfile
  Dockerfile.ACC
Labels: bug, ci
