Repository planetarium/NineChronicles.Headless, pull requests merged in 2024-01, with the labels that each got.

#2368 update multiaccount management middleware
  NineChronicles.Headless/GraphQLService.cs
  NineChronicles.Headless/HostBuilderExtensions.cs
  NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
  NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
  NineChronicles.Headless/Middleware/IpBanMiddleware.cs
Labels: Small

#2372 Increase acc max quota
  NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
Labels: Extra Small

#2373 Add devforum badge to README
  README.md
Labels: documentation, Extra Small

#2375 🔧 [Libplanet 4.0] Fix query tests
  NineChronicles.Headless.Tests/Common/MockAccountState.cs
  NineChronicles.Headless/GraphTypes/StateQueryFields/Garages.cs
Labels: Extra Small

#2387 Add upgrade/libplanet-4.0 branch on workflow to push docker image
  .github/workflows/push_docker_image.yml
Labels: Extra Small

#2393 Fix NRE on byte encodings on BlockChainService
  NineChronicles.Headless/BlockChainService.cs
Labels: Extra Small
