Repository planetarium/NineChronicles.Headless, pull requests merged in 2024-05, with the labels that each got.

#2469 Add Libplanet.Mocks project to solution
  NineChronicles.Headless.Executable.sln
Labels: bug

#2467 add `--consensus-propose-second-base` cli parameter
  Libplanet.Headless/Hosting/LibplanetNodeService.cs
  Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
  NineChronicles.Headless.Executable/Configuration.cs
  NineChronicles.Headless.Executable/Program.cs
  NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
Labels: cli, configuration

#2477 Provide `index` parameter when to query state
  NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
Labels: api/graphql

#2478 Correct typo
  Libplanet.Extensions.ForkableActionEvaluator/HardForkRouter.cs
  hooks/pre-commit
Labels: bug
